In [1]:
import pandas as pd
import tkinter
from tkinter import filedialog
import numpy as np
tkinter.Tk().withdraw() # prevents an empty tkinter window from appearing
file_name = filedialog.askopenfilename()

df = pd.read_pickle(file_name)

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)

In [2]:
display(df)
#pd.reset_option('all')

                   Name         lam Radius Values End Condition
0         dias_inf_vc_0    5.856582  [5.09, 5.09]        [1, 2]
1         dias_inf_vc_1    0.379175  [5.09, 5.09]        [3, 4]
2   liver_veins_hep36_0   42.397436  [2.34, 2.34]            ST
3         dias_inf_vc_2    0.282908  [5.09, 5.09]        [5, 6]
4   liver_veins_hep16_0   35.481183  [3.72, 1.98]            ST
5         dias_inf_vc_3   25.288802  [5.09, 5.09]        [7, 8]
6   liver_veins_hep31_0   35.935961  [4.06, 1.99]            ST
7         dias_inf_vc_4    3.518664  [5.09, 5.09]       [9, 10]
8      lkidney_veins0_0   35.344538  [2.38, 2.38]            ST
9         dias_inf_vc_5   15.713163  [5.09, 5.09]      [11, 12]
10     rkidney_veins0_0   12.805195  [2.31, 2.31]            ST
11        dias_inf_vc_6   10.899804  [5.09, 5.09]          [13]
12            veins19_0   27.522648  [2.87, 2.87]      [14, 15]
13       veins_rleg27_0    3.656863  [4.08, 4.07]      [16, 17]
14            veins19_1   15.363057  [3.14, 3.14]            ST
15        veins_lleg9_0   45.565868  [3.34, 3.07]      [18, 19]
16       veins_rleg27_1   36.918919  [4.07, 3.29]      [20, 21]
17            veins31_0   24.641425  [4.49, 3.75]            ST
18        veins_lleg9_1    1.385621  [3.06, 3.06]      [22, 23]
19        veins_lleg1_0   55.363095   [1.68, 1.4]            ST
20       veins_rleg27_2    0.444785  [3.26, 3.26]      [24, 25]
21        veins_rleg1_0   58.254658  [1.61, 1.35]            ST
22        veins_lleg9_2  363.302721  [2.94, 0.46]            ST
23       veins_lleg17_0  675.979592  [1.47, 1.45]            ST
24       veins_rleg27_3  343.842949   [3.12, 0.5]            ST
25       veins_rleg16_0      451.25   [2.2, 0.71]            ST

In [3]:
df_cb = df['Name']
df_cb.to_clipboard(sep=',', index=False)

In [4]:
length = []


for i in range(0, np.shape(df)[0]):
    lam = df.at[i,'lam']
    Ru = df.at[i, 'Radius Values'][0]
    L = lam * Ru / 10
    length=np.append(length, L )

df.insert(2, "Length", length, True)

In [6]:
# length_df = df.sort_values(by=['Length'])
display(df)

                   Name         lam   Length Radius Values End Condition
0         dias_inf_vc_0    5.856582    2.981  [5.09, 5.09]        [1, 2]
1         dias_inf_vc_1    0.379175    0.193  [5.09, 5.09]        [3, 4]
2   liver_veins_hep36_0   42.397436    9.921  [2.34, 2.34]            ST
3         dias_inf_vc_2    0.282908    0.144  [5.09, 5.09]        [5, 6]
4   liver_veins_hep16_0   35.481183   13.199  [3.72, 1.98]            ST
5         dias_inf_vc_3   25.288802   12.872  [5.09, 5.09]        [7, 8]
6   liver_veins_hep31_0   35.935961   14.590  [4.06, 1.99]            ST
7         dias_inf_vc_4    3.518664    1.791  [5.09, 5.09]       [9, 10]
8      lkidney_veins0_0   35.344538    8.412  [2.38, 2.38]            ST
9         dias_inf_vc_5   15.713163    7.998  [5.09, 5.09]      [11, 12]
10     rkidney_veins0_0   12.805195    2.958  [2.31, 2.31]            ST
11        dias_inf_vc_6   10.899804    5.548  [5.09, 5.09]          [13]
12            veins19_0   27.522648    7.899  [2.87, 2.87]      [14, 15]
13       veins_rleg27_0    3.656863    1.492  [4.08, 4.07]      [16, 17]
14            veins19_1   15.363057    4.824  [3.14, 3.14]            ST
15        veins_lleg9_0   45.565868   15.219  [3.34, 3.07]      [18, 19]
16       veins_rleg27_1   36.918919   15.026  [4.07, 3.29]      [20, 21]
17            veins31_0   24.641425   11.064  [4.49, 3.75]            ST
18        veins_lleg9_1    1.385621    0.424  [3.06, 3.06]      [22, 23]
19        veins_lleg1_0   55.363095    9.301   [1.68, 1.4]            ST
20       veins_rleg27_2    0.444785    0.145  [3.26, 3.26]      [24, 25]
21        veins_rleg1_0   58.254658    9.379  [1.61, 1.35]            ST
22        veins_lleg9_2  363.302721  106.811  [2.94, 0.46]            ST
23       veins_lleg17_0  675.979592   99.369  [1.47, 1.45]            ST
24       veins_rleg27_3  343.842949  107.279   [3.12, 0.5]            ST
25       veins_rleg16_0      451.25   99.275   [2.2, 0.71]            ST